import { ThemeProvider } from '@/components/ThemeProvider';
import '../styles/globals.css';
import { fontMono, fontSans } from '@/components/Fonts';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import Provider from '@/components/Provider/Provider';
import AsideNav from '@/components/Navbar/AsideNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen font-sans antialiased flex',
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <Provider>
          <AsideNav className="w-[15rem]" />
          {children}
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
