import { ThemeProvider } from '@/components/ThemeProvider';
import '../styles/globals.css';
import { fontMono, fontSans } from '@/components/Fonts';
import type { Metadata } from 'next';
import { cn } from '@/lib/utils';
import AuthProvider from '@/components/AuthProvider';
import { Session } from 'next-auth';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
};

async function getSession(cookie: string): Promise<Session> {
  const response = await fetch('http://localhost:3000/api/auth/session', {
    headers: {
      cookie,
    },
  }
);

  const session = await response.json();

  return Object.keys(session).length > 0 ? session : null;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession(headers().get('cookie') ?? '');
  console.log(session)

  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen font-sans antialiased',
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <AuthProvider >{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
